default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instadate_api_development
  host: localhost

test:
  <<: *default
  database: instadate_api_test

production:
  <<: *default
  database: instadate_api_production
  username: instadate_api
  password: <%= ENV['INSTADATE_API_DATABASE_PASSWORD'] %>
